# Docker Compose for Development Environment
# Hot-reload enabled for rapid development

version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        NEXT_PUBLIC_SUPABASE_URL: ${NEXT_PUBLIC_SUPABASE_URL}
        NEXT_PUBLIC_SUPABASE_ANON_KEY: ${NEXT_PUBLIC_SUPABASE_ANON_KEY}
    image: crypt-front:dev
    container_name: crypt-front-dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      - WATCHPACK_POLLING=true
    volumes:
      # Mount source code for hot reload
      - ./app:/app/app
      - ./components:/app/components
      - ./hooks:/app/hooks
      - ./lib:/app/lib
      - ./public:/app/public
      # Mount config files
      - ./next.config.ts:/app/next.config.ts
      - ./tsconfig.json:/app/tsconfig.json
      - ./tailwind.config.ts:/app/tailwind.config.ts
      - ./postcss.config.mjs:/app/postcss.config.mjs
      # Prevent node_modules from being overwritten
      - /app/node_modules
      - /app/.next
    networks:
      - dev-network
    # Development doesn't need strict resource limits
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  dev-network:
    driver: bridge
